
name: Trigger CKB Platform

on:
  push:
    branches:
    - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger CKB Platform
      run: |
        curl -X POST           -H "Content-Type: application/json"           -d '{"commit": "${{ github.sha }}", "repository": "${{ github.repository }}"}'           https://dl529nfz-8000.euw.devtunnels.ms/tgms/trigger
                    